image:
  repository: ghcr.io/poisoned-monkey/terrarium
  tag: ""  # defaults to Chart.appVersion
  pullPolicy: IfNotPresent

replicaCount: 1

leaderElect: true

syncReceiver:
  image: ghcr.io/poisoned-monkey/terrarium/sync-receiver:latest

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 256Mi

serviceAccount:
  create: true
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}
